move_arm_node:
  ros__parameters:
    num_joints: 4 # Aquí defines el tamaño de current_angles_
    
rviz_bridge_node:
  ros__parameters:
    joint_names: [
      "joint_base_to_c1", 
      "joint_c1_to_c2", 
      "joint_c2_to_c3", 
      "joint_c3_to_izq"
    ]
servo_bridge_node:
  ros__parameters:
    num_joints: 4 # Aquí defines el tamaño de current_angles_
    

